const CMS_ADMIN_COPY = {
	en: {
		locales: { en: 'English', es: 'Español', pt: 'Português' },
		pageBuilder: 'Page Builder',
		pageBuilderIntro:
			'Build tenant-specific live pages, control access by role, and inject them into the site menus automatically.',
		createPage: 'Create page',
		createCmsPage: 'Create CMS Page',
		editCmsPage: 'Edit CMS Page',
		editorIntro:
			'Pages save directly live. Menu visibility and route access are derived from the same record, so preview matches production.',
		previewPage: 'Preview page',
		saveLive: 'Save live',
		saving: 'Saving...',
		delete: 'Delete',
		deleting: 'Deleting...',
		deleteConfirm: 'Delete this page? This goes live immediately.',
		pageCreated: 'Page created.',
		pageUpdated: 'Page updated.',
		pageDeleted: 'Page deleted.',
		pageTitleRequired: 'Page title is required.',
		pageSlugRequired: 'A page slug is required.',
		addSectionRequired: 'Add at least one section.',
		saveFailed: 'Could not save page.',
		deleteFailed: 'Could not delete page.',
		pageTitle: 'Page title',
		slug: 'Slug',
		menuLabel: 'Menu label',
		menuIcon: 'Menu icon',
		pageSummary: 'Page summary',
		rendersAt: 'Renders at',
		access: 'Access',
		grantPublicAccess: 'Grant public access',
		publicAccessHelp: 'Anyone can open this page without signing in.',
		grantSignedInAccess: 'Grant signed-in access',
		signedInAccessHelp:
			'Checked roles can access the page when it is not public. Unchecked roles are blocked.',
		publicAccessStillApplies:
			'Public access already allows everyone to open the page. These role grants still matter if you later turn public access off.',
		menus: 'Menus',
		showInMenus: 'Show in menus',
		showInMenusHelp: 'Allow this page to appear in navigation.',
		menuPlacement: 'Menu placement',
		menuPlacementHelp:
			'Check the menus where this page should appear. A link only shows to users who can actually access the page.',
		mainMenuHelp: 'Public-facing main navigation',
		workerMenuHelp: 'Worker side navigation',
		adminMenuHelp: 'Admin side navigation',
		ctaButtons: 'CTA Buttons',
		ctaButtonsHelp: 'Add page-level action buttons under the page intro.',
		addCta: 'Add CTA',
		noCtas: 'No CTA buttons yet.',
		label: 'Label',
		link: 'Link',
		variant: 'Variant',
		newTab: 'New tab',
		seo: 'SEO',
		seoHelp: 'Leave blank to fall back to the page title and summary.',
		seoTitle: 'SEO title',
		seoDescription: 'SEO description',
		layout: 'Layout',
		layoutHelp:
			'These tokens shape the live page without requiring custom code.',
		maxWidth: 'Max width',
		heroStyle: 'Hero style',
		background: 'Background',
		sectionSpacing: 'Section spacing',
		sectionSidebar: 'Section sidebar',
		sectionSidebarHelp:
			'Render a sticky section index when headings are present.',
		sections: 'Sections',
		sectionsHelp:
			'All sections are rich text today, but the schema leaves room for more types later.',
		addSection: 'Add section',
		sectionNumber: 'Section',
		sectionHelp:
			'Internal name and heading can differ. Hidden sections stay in the editor but do not render live.',
		up: 'Up',
		down: 'Down',
		remove: 'Remove',
		internalName: 'Internal name',
		heading: 'Heading',
		template: 'Template',
		visible: 'Visible',
		visibleHelp: 'Show this section on the live page.',
		noPages: 'No CMS pages exist for this locale yet.',
		noSummary: 'No page summary added yet.',
		public: 'Public',
		signedIn: 'Signed-in',
		inMenu: 'In menu',
		preview: 'Preview',
		edit: 'Edit',
	},
	es: {
		locales: { en: 'English', es: 'Español', pt: 'Português' },
		pageBuilder: 'Constructor de páginas',
		pageBuilderIntro:
			'Crea páginas activas para cada implementación, controla el acceso por rol y agrégalas automáticamente a los menús del sitio.',
		createPage: 'Crear página',
		createCmsPage: 'Crear página CMS',
		editCmsPage: 'Editar página CMS',
		editorIntro:
			'Las páginas se guardan en vivo. La visibilidad en menús y el acceso a la ruta provienen del mismo registro, por lo que la vista previa coincide con producción.',
		previewPage: 'Vista previa',
		saveLive: 'Guardar en vivo',
		saving: 'Guardando...',
		delete: 'Eliminar',
		deleting: 'Eliminando...',
		deleteConfirm: '¿Eliminar esta página? Este cambio se publica inmediatamente.',
		pageCreated: 'Página creada.',
		pageUpdated: 'Página actualizada.',
		pageDeleted: 'Página eliminada.',
		pageTitleRequired: 'El título de la página es obligatorio.',
		pageSlugRequired: 'El slug de la página es obligatorio.',
		addSectionRequired: 'Agrega al menos una sección.',
		saveFailed: 'No se pudo guardar la página.',
		deleteFailed: 'No se pudo eliminar la página.',
		pageTitle: 'Título de la página',
		slug: 'Slug',
		menuLabel: 'Etiqueta del menú',
		menuIcon: 'Ícono del menú',
		pageSummary: 'Resumen de la página',
		rendersAt: 'Se mostrará en',
		access: 'Acceso',
		grantPublicAccess: 'Conceder acceso público',
		publicAccessHelp: 'Cualquier persona puede abrir esta página sin iniciar sesión.',
		grantSignedInAccess: 'Conceder acceso a usuarios autenticados',
		signedInAccessHelp:
			'Los roles marcados pueden acceder cuando la página no es pública. Los no marcados quedan bloqueados.',
		publicAccessStillApplies:
			'El acceso público ya permite que cualquiera abra la página. Estos permisos por rol siguen importando si luego desactivas el acceso público.',
		menus: 'Menús',
		showInMenus: 'Mostrar en menús',
		showInMenusHelp: 'Permite que esta página aparezca en la navegación.',
		menuPlacement: 'Ubicación en menús',
		menuPlacementHelp:
			'Marca los menús donde debe aparecer esta página. El enlace solo se muestra a usuarios que realmente pueden acceder.',
		mainMenuHelp: 'Navegación principal pública',
		workerMenuHelp: 'Navegación lateral de trabajadores',
		adminMenuHelp: 'Navegación lateral de administración',
		ctaButtons: 'Botones CTA',
		ctaButtonsHelp: 'Agrega botones de acción debajo de la introducción de la página.',
		addCta: 'Agregar CTA',
		noCtas: 'Todavía no hay botones CTA.',
		label: 'Etiqueta',
		link: 'Enlace',
		variant: 'Variante',
		newTab: 'Nueva pestaña',
		seo: 'SEO',
		seoHelp: 'Déjalo en blanco para usar el título y el resumen de la página.',
		seoTitle: 'Título SEO',
		seoDescription: 'Descripción SEO',
		layout: 'Diseño',
		layoutHelp:
			'Estos ajustes definen la página publicada sin requerir código personalizado.',
		maxWidth: 'Ancho máximo',
		heroStyle: 'Estilo del encabezado',
		background: 'Fondo',
		sectionSpacing: 'Espaciado entre secciones',
		sectionSidebar: 'Barra lateral de secciones',
		sectionSidebarHelp:
			'Muestra un índice fijo de secciones cuando existan encabezados.',
		sections: 'Secciones',
		sectionsHelp:
			'Todas las secciones usan texto enriquecido hoy, pero el esquema deja espacio para otros tipos más adelante.',
		addSection: 'Agregar sección',
		sectionNumber: 'Sección',
		sectionHelp:
			'El nombre interno y el encabezado pueden ser distintos. Las secciones ocultas permanecen en el editor pero no se muestran en vivo.',
		up: 'Subir',
		down: 'Bajar',
		remove: 'Quitar',
		internalName: 'Nombre interno',
		heading: 'Encabezado',
		template: 'Plantilla',
		visible: 'Visible',
		visibleHelp: 'Mostrar esta sección en la página publicada.',
		noPages: 'Todavía no existen páginas CMS para este idioma.',
		noSummary: 'Todavía no hay resumen para esta página.',
		public: 'Pública',
		signedIn: 'Con acceso',
		inMenu: 'En menú',
		preview: 'Vista previa',
		edit: 'Editar',
	},
	pt: {
		locales: { en: 'English', es: 'Español', pt: 'Português' },
		pageBuilder: 'Construtor de páginas',
		pageBuilderIntro:
			'Crie páginas ativas por implantação, controle o acesso por função e injete-as automaticamente nos menus do site.',
		createPage: 'Criar página',
		createCmsPage: 'Criar página CMS',
		editCmsPage: 'Editar página CMS',
		editorIntro:
			'As páginas são salvas ao vivo. A visibilidade nos menus e o acesso à rota vêm do mesmo registro, então a visualização corresponde à produção.',
		previewPage: 'Visualizar página',
		saveLive: 'Salvar ao vivo',
		saving: 'Salvando...',
		delete: 'Excluir',
		deleting: 'Excluindo...',
		deleteConfirm: 'Excluir esta página? Isso entra no ar imediatamente.',
		pageCreated: 'Página criada.',
		pageUpdated: 'Página atualizada.',
		pageDeleted: 'Página excluída.',
		pageTitleRequired: 'O título da página é obrigatório.',
		pageSlugRequired: 'O slug da página é obrigatório.',
		addSectionRequired: 'Adicione pelo menos uma seção.',
		saveFailed: 'Não foi possível salvar a página.',
		deleteFailed: 'Não foi possível excluir a página.',
		pageTitle: 'Título da página',
		slug: 'Slug',
		menuLabel: 'Rótulo do menu',
		menuIcon: 'Ícone do menu',
		pageSummary: 'Resumo da página',
		rendersAt: 'Será exibida em',
		access: 'Acesso',
		grantPublicAccess: 'Conceder acesso público',
		publicAccessHelp: 'Qualquer pessoa pode abrir esta página sem fazer login.',
		grantSignedInAccess: 'Conceder acesso para usuários autenticados',
		signedInAccessHelp:
			'As funções marcadas podem acessar a página quando ela não for pública. As não marcadas ficam bloqueadas.',
		publicAccessStillApplies:
			'O acesso público já permite que qualquer pessoa abra a página. Essas permissões por função ainda importam se você desativar o acesso público depois.',
		menus: 'Menus',
		showInMenus: 'Mostrar nos menus',
		showInMenusHelp: 'Permite que esta página apareça na navegação.',
		menuPlacement: 'Posicionamento no menu',
		menuPlacementHelp:
			'Marque os menus onde esta página deve aparecer. O link só é mostrado para usuários que realmente podem acessá-la.',
		mainMenuHelp: 'Navegação principal pública',
		workerMenuHelp: 'Navegação lateral de trabalhadores',
		adminMenuHelp: 'Navegação lateral da administração',
		ctaButtons: 'Botões CTA',
		ctaButtonsHelp: 'Adicione botões de ação abaixo da introdução da página.',
		addCta: 'Adicionar CTA',
		noCtas: 'Ainda não há botões CTA.',
		label: 'Rótulo',
		link: 'Link',
		variant: 'Variante',
		newTab: 'Nova guia',
		seo: 'SEO',
		seoHelp: 'Deixe em branco para usar o título e o resumo da página.',
		seoTitle: 'Título SEO',
		seoDescription: 'Descrição SEO',
		layout: 'Layout',
		layoutHelp:
			'Esses controles moldam a página publicada sem exigir código personalizado.',
		maxWidth: 'Largura máxima',
		heroStyle: 'Estilo do cabeçalho',
		background: 'Fundo',
		sectionSpacing: 'Espaçamento entre seções',
		sectionSidebar: 'Barra lateral de seções',
		sectionSidebarHelp:
			'Renderiza um índice fixo de seções quando houver cabeçalhos.',
		sections: 'Seções',
		sectionsHelp:
			'Todas as seções usam texto rico hoje, mas o esquema deixa espaço para mais tipos no futuro.',
		addSection: 'Adicionar seção',
		sectionNumber: 'Seção',
		sectionHelp:
			'O nome interno e o título podem ser diferentes. As seções ocultas permanecem no editor, mas não aparecem ao vivo.',
		up: 'Subir',
		down: 'Descer',
		remove: 'Remover',
		internalName: 'Nome interno',
		heading: 'Título',
		template: 'Modelo',
		visible: 'Visível',
		visibleHelp: 'Mostrar esta seção na página publicada.',
		noPages: 'Ainda não existem páginas CMS para este idioma.',
		noSummary: 'Ainda não há resumo para esta página.',
		public: 'Pública',
		signedIn: 'Autenticada',
		inMenu: 'No menu',
		preview: 'Visualizar',
		edit: 'Editar',
	},
} as const

export function getCmsAdminCopy(locale: string) {
	return CMS_ADMIN_COPY[locale as keyof typeof CMS_ADMIN_COPY] ?? CMS_ADMIN_COPY.en
}
